[mediapipe_holistic]
min_detection_confidence = 0.5
min_tracking_confidence = 0.5
static_image_mode = false
model_complexity = 1
smooth_landmarks = true
enable_segmentation = false
refine_face_landmarks = false

[keypoint_mapping]
# MediaPipe to our internal naming
nose = 0
left_shoulder = 11
right_shoulder = 12
left_hip = 23
right_hip = 24
left_knee = 25
right_knee = 26

[quality_thresholds]
min_visibility = 0.5
min_confidence = 0.5
required_spine_keypoints = ["nose", "left_shoulder", "right_shoulder", "left_hip", "right_hip"]